### ISSUE TITLE
captcha letters is not well recognized 

### ISSUE THREAD

**Issue by engahmed1190** [tesseract-ocr/tessdata#101]
I am trying to read captcha letters using Tesseract but I failed in some cases like this image

![top](https://user-images.githubusercontent.com/25582838/41201881-85047440-6cc0-11e8-9513-50c1b4487da3.png)

i am using command 

`tesseract top.png output`

tesseract version 

```
tesseract 4.0.0-beta.1-306-g45b11cd
 leptonica-1.76.0
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8
 Found AVX
 Found SSE
```

**Comment by zdenop** [comment]
It is not bug. Tesseract is designed to OCR books and not captch.
