### ISSUE TITLE
Android error “Fatal signal 6 (SIGABRT), code -6 in tid 9961 (ple.myApp)” when using tesstwo

### ISSUE THREAD

**Issue by felisimo** [tesseract-ocr/tessdata#104]
I get the above error when attempting to init a TessBaseAPI object to do some OCR. I supply it with the path to the parent directory of "tessdata". I'm new to android so not very sure what else to provide besides the snippet. Am I even initializing this correctly? Because this snippet is based on a project done a few years ago...so I don't know if any version conflicts could be the cause. 
This error occurs whether debugging or not (the app just crashes) Thank you

```
TessBaseAPI baseApi = new TessBaseAPI();
baseApi.setDebug(true);
baseApi.init(_appDataPath, _language); //THIS IS WHERE IT CRASHES
```

**Comment by zdenop** [comment]
we do not provide support for 3rd party sw.
