### ISSUE TITLE
Missing hin.cube.size

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tessdata#11]
According to the documentation (https://code.google.com/p/tesseract-ocr-extradocs/wiki/Cube), lang.cube.size is required for the cube recognition engine.

Either Hindi (hin) should provide all files needed for the cube recognition engine or none of them (or the documentation is wrong and cube works without lang.cube.size - is there more up to date documentation?).

**Comment by ShivGuitHub** [comment]
Kindly update on following thread. It is critical.

**Comment by Shreeshrii** [comment]
This issue can be closed as cube has been removed.

**Comment by stweil** [comment]
Indeed, thanks.
