### ISSUE TITLE
Pytesseract 4.0 .traineddata on Handwritten Images

### ISSUE THREAD

**Issue by supersaiyan12** [tesseract-ocr/tessdata#112]
I have number of images and wanted to convert into a text using tesseract 4.0.(All are in hand-written english)
_I have 2 query regarding this._
1.Is it possible to create **".traineddata"** from the hand written images that i have.
2.If yes, then how do i get start from the scratch.

Thanks in Advance

**Comment by amitdo** [comment]
@supersaiyan12,

Please use the forum for asking questions.
