### ISSUE TITLE
Cannot find protocol declaration for 'G8TesseractDelegate'

### ISSUE THREAD

**Issue by losheredos** [tesseract-ocr/tessdata#122]
I installed package with required steps such as installing pods and linking but still getting this error. I have no idea how to solve it. 
This error occurs in **RNTesseractOcr.xcodeproj/RNTesseractOcr.h/RNTesseractOcr**

#import "RCTBridgeModule.h"
#import "RNTesseractOcr.h"

@interface RNTesseractOcr : NSObject <RCTBridgeModule, G8TesseractDelegate>

@end

any ideas how to solve it?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
(this is not tesseract header files)

**Comment by losheredos** [comment]
Sorry I think I posted it in wrong place.
