### ISSUE TITLE
How to apply the copyright

### ISSUE THREAD

**Issue by firiona** [tesseract-ocr/tessdata#124]
Copyright must be included in a notice file to apply Apache License in my work.

Copyright [yyyy]  [name of copyright owner]

But It doesn't exist in License file.

Please let me know what is the copyright if my work use tessdata?

Thank you.

**Comment by Shreeshrii** [comment]
I think it would be 

 (C) Copyright 2016, Google Inc.

considering that tessdata was last updated by Ray in 2016 - https://github.com/tesseract-ocr/tessdata/commit/4592b8d453889181e01982d22328b5846765eaad

tessdata_best - 2017
https://github.com/tesseract-ocr/tessdata/commit/3a94ddd47be01fd897cbe31f05cbd2301454cf8a

tessdata_fast - 2017
https://github.com/tesseract-ocr/tessdata_fast/commit/923915d4ced2a7235221788285785a29c4a42d4a

@theraysmith @jbreiden @zdenop Please comment if above is not ok.

**Comment by firiona** [comment]
Can I use below as you said?

Thank you.
--------------------------------------------------------------------------------

(C) Copyright 2016, Google Inc.

considering that tessdata was last updated by Ray in 2016 - 4592b8d

tessdata_best - 2017
3a94ddd

tessdata_fast - 2017
tesseract-ocr/tessdata_fast@923915d

**Comment by stweil** [comment]
@firiona, I think there is a misunderstanding. Are you referring to the part of the license which comes after ["END OF TERMS AND CONDITIONS"](https://github.com/tesseract-ocr/tessdata/blob/master/LICENSE#L177)? That part explains how you can put your own code under the Apache License.

I don't think that it is necessary to cite the Google copyright f you just use traineddata from here.
