### ISSUE TITLE
/usr/local/bin/tesstrain_utils.sh: line 80: syntax error near unexpected token `&'

### ISSUE THREAD

**Issue by eravallirao** [tesseract-ocr/tessdata#125]
Can someone help me, I am getting this error while trying to generate the traindata using below command
**tesstrain.sh --fonts_dir ../../fonts --fontlist 'ABCDEFGHIJKLM' --lang eng --linedata_only --langdata_dir ../../langdata_lstm --tessdta_dir ../../tessdata --save_box_tiff --maxpages 10 --output_dir train**

**Comment by stweil** [comment]
It should be `--tessdata_dir`, not `--tessdta_dir`.

**Comment by eravallirao** [comment]
Sorry, yeah  I cleared it. Thanks
