### ISSUE TITLE
How can I in invoke the tessdata in Matlab?

### ISSUE THREAD

**Issue by xxxingzhe** [tesseract-ocr/tessdata#128]
The official MATLab documentation uses the command "txt = ocr(img,'Language','path/to/tessdata/eng.traineddata')", but an error occurs, "Error using tesseractWrapper
Internal error using Tesseract:
Actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file
..\..\ccutil\tessdatamanager.cpp, line 50
Error ocr>tesseract (line 149)
  [txt, ocrMetadata] = tesseractWrapper(tessOpts, Iu8, hasROI, roi, resetParameters);
Error ocr (line 130)
  [rawtext, metadata] = tesseract(params, img, roi, hasROI);" How do you solve it?

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/FAQ-Old#actual_tessdata_num_entries_-tessdata_num_entrieserrorassert-failedin-file-ccutiltessdatamanagercpp-line-55_
