### ISSUE TITLE
tessedit_load_sublangs

### ISSUE THREAD

**Issue by dbojan** [tesseract-ocr/tessdata#13]
In language file spr_latn.tessdata (Serbian lating) there is a line:
tessedit_load_sublangs srp
which means that tesseract loads srp (Serbian Cyrillic) language file.

As a result some of the text is recognized as cyrillic, even if the original text contains no cyrillic script at all!

Can this option be disabled in any way, or new language files provided without the "load sublangs" part?

Test image is provided
![test](https://cloud.githubusercontent.com/assets/1901895/13563566/fede4042-e442-11e5-9088-18bbfd76725c.png)

(Additional notes:
-Older version of this language file did not have this line.
-"tessedit_load_sublangs" is present in another file, srp_latn.
-in the future, if more than one language is needed, one can select it by typing: -l srp+srp_latn)

Thank you.

**Comment by stweil** [comment]
@zdenop, as far as I see there is currently no branch or tagged release for Tesseract 3.x which includes this fix. Are you planning to add one?
