### ISSUE TITLE
Slovak language tessdata/slk.traineddata not working correctly

### ISSUE THREAD

**Issue by tomasdrgon** [tesseract-ocr/tessdata#130]
Hi there, I would like to ask if there is a way to fix this. I downloaded slk.traineddata for slovak texts, and for special symbols of Slovak language the output is incorrect I tried to use an image with Big letters but it's still doing me this error.

source code : ```
package imagereader;

import org.bytedeco.javacpp.*;
import static org.bytedeco.javacpp.lept.*;
import static org.bytedeco.javacpp.tesseract.*;

public class BasicExample {
    public static void main(String[] args) {
        BytePointer outText;

        TessBaseAPI api = new TessBaseAPI();
       
        // Initialize tesseract-ocr with English, without specifying tessdata path
        if (api.Init("D:\\Program\\tessaract\\", "slv") != 0) {
            System.err.println("Could not initialize tesseract.");
            System.exit(1);
        }

        // Open input image with leptonica library
        PIX image = pixRead(args.length > 0 ? args[0] : "D:\\scanExample.jpg");
        api.SetImage(image);
        // Get OCR result
        outText = api.GetUTF8Text();
        System.out.println("OCR output:\n" + outText.getString());

        // Destroy used object and release memory
        api.End();
        outText.deallocate();
        pixDestroy(image);
    }
}```
OCR output:
ANGLICKO

SLOVENSKY
PÄŚDO ,
HOSPODARSKY

SLOVNI'K

and the image : 
![scanExample](https://user-images.githubusercontent.com/10038231/66418022-83495980-ea01-11e9-80e7-5ff74ac54f77.jpg)

**Comment by zdenop** [comment]
1. We do not support 3rd project => use tesseract executable for reporting problem.
2. Specified tesseract version => make sure you use the latest version
3. Read the docs. 

My results are this:
```
tesseract 66418022-83495980-ea01-11e9-80e7-5ff74ac54f77.jpg - -l slk
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 414


ANGLICKO
SLOVENSKÝ

PÔDO —
HOSPODÁRSKY
SLOVNÍK
```
So the error is on your side. Use tesseract user forum for asking support.
