### ISSUE TITLE
It does not allow selecting languages

### ISSUE THREAD

**Issue by jalle007** [tesseract-ocr/tessdata#131]
whats wrong with this library ?

 const config = {
      lang: 'bos',
    }

 Tessaract.recognize(this.selectedImage, config)...

??????????????????????????????????????????????????????
error downloading
tessdata.projectnaptha.com/3.02./bos.traineddata.gz

**Comment by zdenop** [comment]
We do not  provide support for 3rd project. You need to contact your project creator.

**Comment by jalle007** [comment]
this library has some serious issues that are nowhere documented.
setting language file
making it work in offline mode

i am talking about Ionic app
