### ISSUE TITLE
crash in nativeInitOem

### ISSUE THREAD

**Issue by liaosongmao** [tesseract-ocr/tessdata#133]
Build fingerprint: @nubia/NX629J/NX629J:9/PKQ1.190321.001/eng.nubia.20191024.085622:user/release-keys@
Revision: @0@
ABI: @arm64@
pid: 14452, tid: 5781, name: pool-1-thread-1 >>> com.test.demo <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0 0000000000000000 x1 0000000000001695 x2 0000000000000006 x3 0000000000000008
    x4 ff092f33381f646d x5 ff092f33381f646d x6 ff092f33381f646d x7 7f7f7f7f7f7f7f7f
    x8 0000000000000083 x9 b1e06469bcaaa71e x10 0000000000000000 x11 fffffffc7ffffbdf
    x12 0000000000000001 x13 0000000000000000 x14 000000753ebf8ea0 x15 0000000000000001
    x16 00000075dd3dd2a8 x17 00000075dd2fcc64 x18 0000000000000010 x19 0000000000003874
    x20 0000000000001695 x21 000000753ebf96ae x22 000000753ebf969a x23 000000753ebfb588
    x24 000000753d3870e0 x25 000000753e4573be x26 0000007539563e80 x27 000000000000009f
    x28 0000000000000002 x29 000000753ebf9570
    sp 000000753ebf9530 lr 00000075dd2f0354 pc 00000075dd2f037c

backtrace:
    #00 pc 000000000002237c /system/lib64/libc.so (abort+116)
    #01 pc 000000000015140c /system/app/demo.apk (offset 0x2c6000) (ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const+352)
    #02 pc 000000000017c968 /system/app/demo.apk (offset 0x2c6000) (tesseract::Classify::ReadIntTemplates(__sFILE*)+2564)
    #03 pc 0000000000160ad8 /system/app/demo.apk (offset 0x2c6000) (tesseract::Classify::InitAdaptiveClassifier(bool)+256)
    #04 pc 00000000002643e4 /system/app/demo.apk (offset 0x2c6000) (tesseract::Wordrec::program_editup(char const*, bool, bool)+56)
    #05 pc 00000000000f6218 /system/app/demo.apk (offset 0x2c6000) (_ZN9tesseract9Tesseract23init_tesseract_internalEPKcS2_S2_NS_13OcrEngineModeEPPciPK13GenericVectorI6STRINGESA_b+232)
    #06 pc 00000000000f5c58 /system/app/demo.apk (offset 0x2c6000) (_ZN9tesseract9Tesseract14init_tesseractEPKcS2_S2_NS_13OcrEngineModeEPPciPK13GenericVectorI6STRINGESA_b+568)
    #07 pc 00000000000a4060 /system/app/demo.apk (offset 0x2c6000) (_ZN9tesseract11TessBaseAPI4InitEPKcS2_NS_13OcrEngineModeEPPciPK13GenericVectorI6STRINGESA_b+288)
    #08 pc 00000000002694a4 /system/app/demo.apk (offset 0x2c6000) (Java_com_googlecode_tesseract_android_TessBaseAPI_nativeInitOem+136)
    #09 pc 0000000000009854 /system/app/demo/oat/arm64/demo.odex (offset 0x9000) (com.googlecode.tesseract.android.TessBaseAPI.nativeInitOem+196)
    #10 pc 0000000000557588 /system/lib64/libart.so (art_quick_invoke_stub+584)
    #11 pc 00000000000cf6d4 /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #12 pc 000000000027ff08 /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #13 pc 000000000027b018 /system/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+748)
    #14 pc 0000000000529208 /system/lib64/libart.so (MterpInvokeDirectRange+248)
    #15 pc 0000000000549f14 /system/lib64/libart.so (ExecuteMterpImpl+15252)
    #16 pc 00000000000c50d2 /system/app/demo/oat/arm64/demo.vdex (com.googlecode.tesseract.android.TessBaseAPI.a+492)
    #17 pc 0000000000253754 /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3295094796+488)
    #18 pc 0000000000259248 /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #19 pc 0000000000279ec8 /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #20 pc 00000000005296d8 /system/lib64/libart.so (MterpInvokeVirtualQuick+584)
    #21 pc 000000000054d894 /system/lib64/libart.so (ExecuteMterpImpl+29972)
    #22 pc 00000000000c4ed8 /system/app/demo/oat/arm64/demo.vdex (com.googlecode.tesseract.android.TessBaseAPI.a+2)
    #23 pc 0000000000253754 /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3295094796+488)
    #24 pc 0000000000259248 /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFram

**Comment by zdenop** [comment]
duplicate to #132. We do not support 3rd party projects. You can try to use tesseract user forum, but provide full details to replicate problem not only crash output
