### ISSUE TITLE
Tesseract not recognising character which is in training data for German

### ISSUE THREAD

**Issue by IdiosApps** [tesseract-ocr/tessdata#136]
### Environment
tesseract 4.0.0-54-gb086
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
 Found AVX
 Found SSE
Ubuntu 16.04

### Current Behavior:
German fails to see a character that's in its training data (§)

![secSign](https://user-images.githubusercontent.com/12559216/72979193-bc021880-3dcf-11ea-9ea9-e5adf308a827.jpg)

Samples of text, from the first paragraph of the page:
-l eng:
```
§ Der Europaische Rat stimmt einer Fristverlangerung zu bis zum § 22.
April §
```

-l deu:
```
s Der Europäische Rat stimmt einer Fristverlängerung zu bis zum & 22.
April &
```

-l eng+deu
```
s Der Europaische Rat stimmt einer Fristverlangerung zu bis zum § 22.
April §
```

-l deu+eng
```
s Der Europäische Rat stimmt einer Fristverlängerung zu bis zum & 22.
April §
```

So eng gets 3/3, deu gets 0/3, eng+deu gets 2/3, and deu+eng get 1/3

What's strange here is that the training data does include this character for both these languages:

https://github.com/tesseract-ocr/langdata_lstm/blob/master/eng/eng.training_text
https://github.com/tesseract-ocr/langdata_lstm/blob/master/deu/deu.training_text

`wc -m` for char counts:

deu:
```
11200 §
16939132 total
0.066% §
```
eng:
```
11482 §
14782282 total
0.077% §
```

### Expected Behavior:
German should see a character that's in its training data (§)

### Suggested Fix:
I checked training data to verify training should be OK, but can't see what the issue is.

**Comment by stweil** [comment]
@IdiosApps, `script/Latin` covers Latin script for many European languages and is much more complete. It recognizes most paragraph characters in your text correctly. Like other models it still has problems with short lines and fails to recognize § 7 and § 8.

**Comment by IdiosApps** [comment]
@amitdo @stweil I see - I thought traineddata was updated for German after trainingdata was updated: 

`9ddc24e750eec0994223a9edc3fcb434a2244f3b tessdata-best 14 Sep 2017 Initial import (on behalf of Ray)`
`b1b56d1bc24220b4930e52f46bb94ab197634473 19 Feb 2017 langdata/deu/desiredcharacters Add more desired characters for German`
`ed5410b928a4b645a0add794c17c20a5f5dc232f tessdata-best 1 Feb 2018 deu: Remove unwanted dependency`

I searched this as I knew that tessdata-best is based on langdata thanks to https://github.com/tesseract-ocr/tesseract/wiki/Data-Files

**Comment by IdiosApps** [comment]
@stweil ancient issue, I'm curious if the trained data was updated? 😁

**Comment by stweil** [comment]
I'm afraid not. And I also don't know another better model for modern German. My own models for historic German prints don't deliver better results. The reason is quite simple: the paragraph sign occurs rarely in the training data, so the neural network does not learn it well enough.
