### ISSUE TITLE
tiffbpl is too small

### ISSUE THREAD

**Issue by mxm2776** [tesseract-ocr/tessdata#137]
I try train myself data. After I use jTessBoxEditor to generate tiff, I use the commind "
 tesseract /Users/tmac/Desktop/chen2.tif chen -l eng  batch.nochop makebox", and remind "Error in pixReadFromTiffStream: bad tiff file: tiffbpl is too small" , what is the matter ???

**Comment by zdenop** [comment]
1. This is leptonica error we can not do nothing with it. Report it on [right place](https://github.com/DanBloomberg/leptonica/issues).
2. You did not share tiff file - nobody can help you... (Is generated tiff file correct? did you use the same lilbtiff version for creating and reading file?)
