### ISSUE TITLE
Tesseract doesn't recognize "0" and "6" in this image

### ISSUE THREAD

**Issue by dream811** [tesseract-ocr/tessdata#139]
![image](https://user-images.githubusercontent.com/45660446/84733501-fb284480-afd0-11ea-9f54-882138cea65c.png)

![image](https://user-images.githubusercontent.com/45660446/84733380-a7b5f680-afd0-11ea-800e-cd00fc99ee0a.png)
0->2
6->5
so my result is "457274"
How can I resolve this issue?
Is there any option to change font?

**Comment by zdenop** [comment]
Use tesseract user forum for asking support
