### ISSUE TITLE
micr tessdata

### ISSUE THREAD

**Issue by alexpandy** [tesseract-ocr/tessdata#14]
There is mcr.traineddata available already. Is it worth to include the same from the below link in the listed traineddata which will be useful

 I have downloaded 'https://groups.google.com/forum/#!msg/tesseract-ocr/obWI4cz8rXg/9glPuTdRX5EJ'

**Comment by zdenop** [comment]
traineddata provided by 3rd party should be maintained by 3rd party (there of outside of project repository)
