### ISSUE TITLE
Spanish traineddata name

### ISSUE THREAD

**Issue by lagunero23** [tesseract-ocr/tessdata#141]
Hello. You can see that in all the traineddata language files, the first two letters are the same as the correspondent ISO 639-1 code. Yes, all of them but one: the spanish language ISO 639-1 spanish is "es" and the traineddata, I really don't know why, it's "spa". I think no harm would be involved in calling the filename "esp.traineddata", no other file is called that name so far. This makes programming so very easier, because the app could match for example ocr trained data with Windows ISpellChecker interface, just to name one example. Of course that I can change it in my distribution, but it seems to me just a discrimination, unless it's motivated by something, but I just can't see what this can be. Thanks.

**Comment by stweil** [comment]
ISO 639-1 are 2-letter codes, but Tesseract uses 3-letter codes.

According to https://www.loc.gov/standards/iso639-2/php/code_list.php, `spa` is the correct ISO 639-2 code for Spanish. So that seems to be correct.

**Comment by lagunero23** [comment]
Well, yes, that's the 639-2, but, at least in Windows, all locale translations use the word "es", that's 639-1. I don't know then if Windows should be considered mainly or not, that's up to you, I guess.

**Comment by lagunero23** [comment]
I guess the discrimination then it's made by ISO.

**Comment by stweil** [comment]
That's a general problem with different standards. I'm afraid we cannot solve it, so we have to live with it, yes.

**Comment by stweil** [comment]
Anyway, you can copy or link `spa.traineddata` to `es.traineddata` and run your local Tesseract with `-l es` then. That would even make the generated hOCR or ALTO files a little bit smaller. :-)

**Comment by lagunero23** [comment]
Thanks, not a very big deal.
