### ISSUE TITLE
osd.trainedData for orientation detection

### ISSUE THREAD

**Issue by kamrapooja** [tesseract-ocr/tessdata#142]
I am using TessBaseAPIDetectOrientationScript to detect orientation and script. Before calling this API i have called TessBaseAPIInit4 to initialize tesseract. In this api path of tessdata repostiory is required.
If osd.trainedData is not present in this folder, still api is getting correct results.
What is the use of osd.trainedata?

Also how can i get skew angle of image with orientation angle.
Please help.

**Comment by kamrapooja** [comment]
Please help.

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
