### ISSUE TITLE
ita.special-words still missing

### ISSUE THREAD

**Issue by Jmuccigr** [tesseract-ocr/tessdata#145]
Three years later, #18 is still occurring.

**Comment by stweil** [comment]
Yes. But why do you open a new issue?

**Comment by Jmuccigr** [comment]
Because the very old one was closed a while back and tesseract is at a new version number.

**Comment by emre-demircan** [comment]
> Because the very old one was closed a while back and tesseract is at a new version number.

Any update about this error?

**Comment by Jmuccigr** [comment]
How should I interpret the closing of this issue?

**Comment by stweil** [comment]
I closed issue #145 because it is only a reference to issue #18, so any discussion can continue there (no matter whether that one is closed or not).

**Comment by stweil** [comment]
Meanwhile I could confirm that there was a regression, so the fixed issue #18 occurred again. See my comment there.
