### ISSUE TITLE
Should there be a release made?

### ISSUE THREAD

**Issue by datalogics-kam** [tesseract-ocr/tessdata#151]
There are some important fixes like https://github.com/tesseract-ocr/tessdata/commit/4767ea922bcc460e70b87b1d303ebdfed0897da8, but there isn't a release that includes it.

We'd normally take the data from a tag or a release tarball.

**Comment by stweil** [comment]
Related: https://github.com/tesseract-ocr/tessdata_fast/issues/26. Please continue the discussion there.

**Comment by stweil** [comment]
Thanks for the reminder. See new [release 4.1.0](https://github.com/tesseract-ocr/tessdata/releases/tag/4.1.0) now.
