### ISSUE TITLE
ces-traineddata causes crash

### ISSUE THREAD

**Issue by jansilar** [tesseract-ocr/tessdata#16]
When using ces-traineddata (downloaded recently from github) in tesseract-ocr trough FreeOCR, tesseract-ocr crashes. I don't know version of tesseract-ocr, but it is commeing with recent FreeOCR 5.41. Other languages (english and swedish tested works). Tested on windows 8.

**Comment by zdenop** [comment]
Read [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice). We do not provide support for FreeOCR.
