### ISSUE TITLE
Failed to load list of training filenames from data/eng/list.train

### ISSUE THREAD

**Issue by xReniar** [tesseract-ocr/tessdata#175]
Hi Guys,

I'm trying to fine tune tesseract  I don't know why I'm getting this error.
This is the output

lstmtraining \
  --debug_interval 0 \
  --traineddata data/eng/eng.traineddata \
  --old_traineddata /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata \
  --continue_from data/eng/eng.lstm \
  --learning_rate 0.0001 \
  --model_output data/eng/checkpoints/eng \
  --train_listfile data/eng/list.train \
  --eval_listfile data/eng/list.eval \
  --max_iterations 10000 \
  --target_error_rate 0.01
Failed to load list of training filenames from data/eng/list.train
make: *** [Makefile:327: data/eng/checkpoints/eng_checkpoint] Error 1

**Comment by zdenop** [comment]
> Failed to load list of training filenames from data/eng/list.train
Did you check the file?

**Comment by xReniar** [comment]
Yes, it's empty and I don't know why

**Comment by Sairahul07-25** [comment]
how did you solve this problem, could you elaborate more

**Comment by xReniar** [comment]
I don't remember anymore what I did, I just used ```make training MODEL_NAME=<MODEL_NAME>```. I think I added wrong parameters to the command
