### ISSUE TITLE
ita.special-words missing

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tessdata#18]
https://github.com/tesseract-ocr/langdata/tree/master/ita

https://github.com/tesseract-ocr/langdata/blob/master/ita/ita.config

```
user_words_suffix special-words
```

https://github.com/tesseract-ocr/langdata/blob/master/ita/ita.special-words
We probably need to put this file in this (`tessdata`) repo and tell the users of `ita.traineddata` that they also need this file.

https://groups.google.com/forum/#!topic/tesseract-ocr/dkwdLLMheFs

**Comment by amitdo** [comment]
I wonder why these two words are separated from the regular wordlist.

```
po'
po`
```

**Comment by Jmuccigr** [comment]
So what's the status of this? It's not a big deal given that there are only two words in this file, but the error is annoying. Should the special-words file be included in this repo?

**Comment by stweil** [comment]
Maybe `ita.config` and `ita.special_words` should simply be removed from https://github.com/tesseract-ocr/langdata/tree/master/ita.

**Comment by stweil** [comment]
I removed the two files in a new pull request for `langdata`. `ita.traineddata` could be fixed similarly (expand, remove two components, combine again).

**Comment by Shreeshrii** [comment]
oops, I suggested opening an issue, didn't realize one was already there.

Do those two words in the special-words file improve recognition for
Italian? If so there would be a reason to keep them.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
> ita.traineddata could be fixed similarly (expand, remove two components,
combine again).

Please create a PR for that also for 3.05 as well as master. Thanks!




ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by stweil** [comment]
> Do those two words in the special-words file improve recognition for Italian? If so there would be a reason to keep them.

The first word `po'` was already part of `ita.wordlist`, so I don't expect that it changed anything.

The second word does not look useful, and as most users did not have `ita.special-words`, the only effect they have seen is an annoying warning message.

**Comment by stweil** [comment]
> Please create a PR for that also for 3.05 as well as master.

There is a simple problem: currently there is no branch for such a PR, so I cannot create a PR for 3.05. @zdenop, could you please create the missing 3.05 branches for `langdata` and `tessdata`?

**Comment by Jmuccigr** [comment]
The second word is just an accentual variant on the first. It's actually the correct form, but the first is both commonly used and will be what tesseract reads.

**Comment by Jmuccigr** [comment]
This is still happening and since the new issue I opened was closed, I guess I should comment here.

**Comment by stweil** [comment]
Yes, please comment here. I now found this history for `tessdata`:

- The issue was fixed in commit 71689a2a0157344ce09fe380f81a6777c22f4852 (2017-06-05).
- It was introduced again in commit d87b3cbc75555bd3282e0cadab5e159e2d468396 (2018-03-22). 
- I fixed it now again with commit 4767ea922bcc460e70b87b1d303ebdfed0897da8.

Commit https://github.com/tesseract-ocr/tessdata_best/commit/e2aad9b983032bb1beff9133104a67cdbb87ca4d fixes the same problem for `tessdata_best`.

`tessdata_fast` does not have this issue.

@Jmuccigr, thank you for reporting this regression. Please test the updated models and report if there remain problems.

**Comment by Jmuccigr** [comment]
Would love to help on this, but I use tesseract new homebrew, so I don't have a local copy I can test on.

Ignoring the special-words file should take care of it though.

**Comment by stweil** [comment]
Homebrew installs `tessdata_fast`, so I wonder why you got that issue at all. Maybe you can check the output from `ls -l /usr/local/Cellar/tesseract/4.1.1/share/tessdata` to see which `ita.traineddata` is installed.

**Comment by Jmuccigr** [comment]
> Homebrew installs tessdata_fast, so I wonder why you got that issue at all. Maybe you can check the output from ls -l /usr/local/Cellar/tesseract/4.1.1/share/tessdata to see which ita.traineddata is installed.

I don't actually find tessdata_fast in homebrew, at least with that name, so I'm not sure what you mean here. 

How does the ls help here? The file is dated Dec 30, 2019.

**Comment by stweil** [comment]
Homebrew provides two "formulae", `tesseract` for the software, [`tesseract-lang`](https://formulae.brew.sh/formula/tesseract-lang) for the model files. `tesseract-lang` installs `ita.traineddata` from Tesseract's `tessdata_fast` repository.

The file date does not help, but the size in bytes is a good indicator which allows telling the source.

**Comment by Jmuccigr** [comment]
> Homebrew provides two "formulae", `tesseract` for the software, [`tesseract-lang`](https://formulae.brew.sh/formula/tesseract-lang) for the model files. `tesseract-lang` installs `ita.traineddata` from Tesseract's `tessdata_fast` repository.
> 
> The file date does not help, but the size in bytes is a good indicator which allows telling the source.

If you'd said that at the start, I would have given it right away. :-)

I've installed tesseract, not tesseract-lang.

File size for the ita.traineddata is 15951701.

**Comment by stweil** [comment]
That's the model from `tessdata`. Just replace it by the [latest fixed one](https://github.com/tesseract-ocr/tessdata/raw/master/ita.traineddata).

**Comment by Jmuccigr** [comment]
OK, I'll do that. Hopefully the fix gets implemented though, otherwise the next update will kill it.
