### ISSUE TITLE
Avoid Tesseract download data

### ISSUE THREAD

**Issue by vanishrao** [tesseract-ocr/tessdata#19]
Hello, 

I am using the javascript version of Tesseract to create a simple web page that allows users to extract text from Image. As I am working on a really slow connection, is it possible for me to somehow avoid tesseract download the traineddata? 

Thanks in advance.

**Comment by BoubakrEchieb** [comment]
Just for the first use Tesseract  download the "tessdata" for the language that you want to recognize

**Comment by zdenop** [comment]
Tesseract does not download any data.

**Comment by BoubakrEchieb** [comment]
zdenop  are you sure?  i made android app using Tesseract and dawnload some data to use in the recognition from here: https://github.com/tesseract-ocr/tessdata

**Comment by zdenop** [comment]
Really? Than please show me [tesseract code](https://github.com/tesseract-ocr/tesseract)  that download data.

**Comment by BoubakrEchieb** [comment]
hhhhh

**Comment by vanishrao** [comment]
@zdenop: I am using a javascript version of tesseract. That downloads eng.traineddata.gz from the tessdata repository if my language is eng. 
@BoubakrEchieb; Thank you so much.. :)

**Comment by vanishrao** [comment]
@BoubakrEchieb: Are there any reduced size traineddata ?? Or any possible ways in which I may reduce my data usage??

**Comment by zdenop** [comment]
This project has no support for javavascript. You should report your issue to author of "javascript version of tesseract".

**Comment by BoubakrEchieb** [comment]
@vanishrao : i don't think that there any kind of reduced traineddata.. but there a way to reduce data usage,just  for the first use Tesseract download  the trained for the language that you want to recognize.
