### ISSUE TITLE
About Persian(fas) Language  

### ISSUE THREAD

**Issue by orkideh** [tesseract-ocr/tessdata#22]
Hello,
I am new to this nice project and i need to use it for my language but the only thing that i found for Persian(fas) language was just one file and after checking result was really disappointing i guess it need to provide more data or train.
Would you mind please help me to get to know how it is possible to make it more accurate ?
Thank you.

**Comment by zdenop** [comment]
1. Use tessact forum for asking support
2. Read [wiki](https://github.com/tesseract-ocr/tesseract/wiki) (e.g. FAQ) before asking any question
