### ISSUE TITLE
Multiple files for arabic and hindi

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tessdata#24]
There are multiple files that are there for ara and hin . Just downloading the traineddata for these languages is not enough.

Downloading multiple files on Windows is difficult.

I would suggest if all required files for these two languages can also be provided as a single zip file - one for each language.

Thanks!

**Comment by Shreeshrii** [comment]
The above is applicable only to 3.05dev branch now.

**Comment by zdenop** [comment]
1. This is task for packagers.
2. Tessdata are already big and increase them by duplicating data in zip archive will problem just increase.
3. Problem is "solved" in next release (4.00) by removing cube.
