### ISSUE TITLE
German dataset seems to have issues

### ISSUE THREAD

**Issue by Phenarc** [tesseract-ocr/tessdata#29]
Calling tesseract with the option -l deu results in the following error messages on the console.

> ParamsModel::Incomplete line 
> ParamsModel::Incomplete line ConvNL„
> ParamsModel::Incomplete line ?êBN¸HÑ?sd¯üÅ?|5LÆ¾•?LNHçþîå¿ˆ!žÉË-±¿wPß¸Î~œ?”HôW;Æ?é‰áé«Â?'Ð=›V«?æÜêqå½?;2ë,£sÓ?©á›¦•˜Ð?S×
> ParamsModel::Incomplete line ó§¿$j¬0Ä¿`èyl¿¿Åçv³2»?³\ý:c²È?uÓ\%Qgâ¿¨Ì!ÉF¯„?êÉ²~é“?q'ÙÕ9b?

With the default eng language option or other languages (e.g. dan) this does not seem to happen.

The program still finishes and produces an output, but the error prevents using tesseract writh wrappers because of the error messages.

Full console output:
[output.txt](https://github.com/tesseract-ocr/tessdata/files/619599/output.txt)

**Comment by stweil** [comment]
Which versions of Tesseract and dataset did you use?

**Comment by Phenarc** [comment]
The newest version found here:
https://github.com/tesseract-ocr/tessdata/blob/master/deu.traineddata

Tesseract 3.05 for Windows from UB Mannheim
https://github.com/UB-Mannheim/tesseract/wiki

**Comment by stweil** [comment]
That's a 3.05 Tesseract with 4.00 traineddata. Maybe that combination is unsupported. Ideally Tesseract should either work with any traineddata or refuse unsupported traineddata.

Does your test work with https://github.com/tesseract-ocr/tessdata/raw/3.04.00/deu.traineddata?

And did you get the error with any image? If not I need your original image to reproduce the problem.

**Comment by Phenarc** [comment]
With this version it works now without problems, thank you.

I figured since it worked with eng and other languages, that it wouldn't be a problem.

**Comment by tom-zeit** [comment]
We encountered the same problem in the last few days.

**Comment by zdenop** [comment]
Days??? New data are available cca 26 hours...
