### ISSUE TITLE
Persian support in Tesseract

### ISSUE THREAD

**Issue by peplamb** [tesseract-ocr/tessdata#3]
Would you be willing to add support for Persian language?

There is an on-going project here https://github.com/reza1615/PersianOcr I tested with "per.traineddata" and it works well on my end.

Thank you

**Comment by zdenop** [comment]
tessdata files are generated by google and they provide support for including langdata.
IMO community trainings (e.g. not supported by google) should be separated from google data.

**Comment by jimregan** [comment]
Persian data may be coming in the future (it was added to langdata).

**Comment by peplamb** [comment]
good news thank you @zdenop and @jimregan

**Comment by theraysmith** [comment]
Persian traineddata and training data is included in tessdata and langdata respectively.
The language code is fas (ISO 639-2T), NOT per, which uses the disfavored ISO 639-2B. (See https://en.wikipedia.org/wiki/Talk%3AISO_639-2).

Having said all that, the accuracy is probably appalling, but I would be happy to know if it works at all.

**Comment by peplamb** [comment]
Awesome!

**Comment by mafshin** [comment]
@theraysmith , the key missing explanation .. fas not per :-)

**Comment by Shreeshrii** [comment]
@peplamb Please test with the latest BEST 4.0alpha traineddata and provide feedback at tesseract-ocr/tessdata#70
