### ISSUE TITLE
Add version info to traineddata files

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tessdata#32]
Since the format of traineddata files is different between 3.xx and 4.xx, it would be helpful to include version info in traineddata files and to also check for compatibility when running tesseract.

**Comment by Shreeshrii** [comment]
@theraysmith Please consider including in next set of changes for 4.0.

**Comment by johnrosenbaud** [comment]
Hello everyone, I was wondering what tessdata files shall be included in the 3.05.00.dev version, the 3.04 or the 4, or something else altogether? Thanks.

**Comment by zdenop** [comment]
@johnrosenbaud: use tesseract user forum for asking questions.

**Comment by amitdo** [comment]
Implemented here:
https://github.com/tesseract-ocr/tesseract/commit/dc8745e6fd4c

**Comment by Shreeshrii** [comment]
Thanks!
