### ISSUE TITLE
How to use tesseract for Persian/Farsi language?

### ISSUE THREAD

**Issue by rezaee** [tesseract-ocr/tessdata#35]
Hi everyone!
I am newbie and like to use tesseract for Persian language, How should I do that? Is there any simple and strightforward tutorial for new users?
I have installed tesseract as they wrote in this tutorial: https://github.com/tesseract-ocr/tesseract/wiki/Compiling, but don't know about usage?

**Comment by zdenop** [comment]
Please use user forum for asking support.

**Comment by rezaee** [comment]
Thanks but where it is? 
May you give me the link?
And say what questions can we ask here?
