### ISSUE TITLE
/sbin/ldconfig.real: /usr/local/lib is not a known library type

### ISSUE THREAD

**Issue by rezaee** [tesseract-ocr/tessdata#36]
Hi
I got this error messages after trying installing tesseract from two ways (source and debian command line):
```
/sbin/ldconfig.real: /usr/local/lib is not a known library type
/sbin/ldconfig.real: /usr/local/lib/pkgconfig is not a known library type
```

What's the problem and how can I fix it?

**Comment by zdenop** [comment]
You got answer [on forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/h7PJfD8BwJ4/7a5LE__hCgAJ).
