### ISSUE TITLE
Dictionary update problem

### ISSUE THREAD

**Issue by ch3bastian** [tesseract-ocr/tessdata#38]
When i downloaded the dictionary from https://github.com/tesseract-ocr/tessdata/spa.traineddata and replaced the 2MB file dictionary with the 24MB it crashes when i try the OCR... perhaps Tesseract need be updated...

![crash](https://cloud.githubusercontent.com/assets/24763257/21471107/43cc5fba-caa5-11e6-91d9-31454eb961e7.jpg)

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.
