### ISSUE TITLE
fra file generates large number of errors

### ISSUE THREAD

**Issue by c3d** [tesseract-ocr/tessdata#39]
After downloading fra.tessdata and putting it in /usr/local/share/tessdata/, I get the following errors:

```
ParamsModel::Incomplete line 
ParamsModel::Incomplete line 
ParamsModel::Incomplete line 
ParamsModel::Incomplete line 
ParamsModel::Incomplete line ConvNL<84>^P
ParamsModel::Incomplete line ܵ<9B><B6><C4><C4>?<CF>^XH<B8><%<D1>?S{E`q<E4><D6>?
<D8>m<AF><BF>ف<D3>?7^Y^Nt<C3><EE><B4>?<8E><D9><C5>u^]<E9>俯^C<A4><B3>0<U+07FB>
<BF><D4>٧ҙ<94><U+063F><D1><C6>S^Sk<9E>տy<EB>^V^?<FA>o<B7><BF>^Y
ParamsModel::Incomplete line '<B6>ĿZ(

```

Version:

```
% tesseract  -v 
tesseract 3.04.01
 leptonica-1.73
  libjpeg 8d : libpng 1.6.26 : libtiff 4.0.7 : zlib 1.2.8

```

Running on macos Sierra ```Darwin 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64```

Installed with `brew install tesseract`.

**Comment by stweil** [comment]
The downloaded file only works with the experimental Tesseract 4.x. You need one from the [3.04 branch](https://github.com/tesseract-ocr/tessdata/tree/3.04.00).

**Comment by c3d** [comment]
> On 27 Dec 2016, at 20:28, Stefan Weil <notifications@github.com> wrote:
> 
> The downloaded file only works with the experimental Tesseract 4.x. You need one from the 3.04 branch.

Ah, OK, I will try this. Thanks.

Christophe

**Comment by c3d** [comment]
Worked for me, you can close
