### ISSUE TITLE
When use chi_sim.trainedddata 3.04, I get an error.

### ISSUE THREAD

**Issue by zhangxiansheng** [tesseract-ocr/tessdata#4]
File "3test.py", line 6, in <module>
    print image_to_string(image,lang="chi_sim").decode("utf8")
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 164, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, 'read_params_file: parameter not found: allow_blob_division')
zyw@arbipher:~/ocr$

**Comment by zdenop** [comment]
Read the FAQ[1] before posting issue.
[1] https://github.com/tesseract-ocr/tesseract/wiki/FAQ

**Comment by weituotian** [comment]
@zdenop why close this issue?

nothing help!!!

**Comment by stweil** [comment]
@weituotian, this is simply not the right place for asking questions and searching for help. Please use the [Tesseract forum](http://groups.google.com/group/tesseract-ocr).

**Comment by weituotian** [comment]
@stweil 
ok, i will ask in the forum
