### ISSUE TITLE
Files Error 

### ISSUE THREAD

**Issue by sofensymbole** [tesseract-ocr/tessdata#42]
These files giving error with Tessract 2.0 jni library.

**Comment by amitdo** [comment]
???

**Comment by stweil** [comment]
@sofensymbole, that's expected behavior. Please read the [documentation](https://github.com/tesseract-ocr/tessdata/blob/master/README.md).

**Comment by sofensymbole** [comment]
Can i get link to download jni library compatilable with these files .

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/AddOns#tesseract-30x

>**Java**: [tess4j](https://github.com/nguyenq/tess4j) - JNA wrapper. Docs and discussions - http://tess4j.sourceforge.net/

It supports (lib)tesseract 3.04.01, so it should be used with older data files.
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-304

**Comment by sofensymbole** [comment]
Can you please  provide me link to download 2.0 compatilbe language files ?

**Comment by amitdo** [comment]
https://sourceforge.net/projects/tesseract-ocr-alt/files/

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-20x
