### ISSUE TITLE
chi_sim error

### ISSUE THREAD

**Issue by LJjack** [tesseract-ocr/tessdata#46]
![123](https://cloud.githubusercontent.com/assets/9940239/21953872/41c3a6e6-da7d-11e6-8f08-241b1d4b60f5.png)
![234](https://cloud.githubusercontent.com/assets/9940239/21953874/45057f50-da7d-11e6-83e8-08eccf9a6ce7.png)

**Comment by zdenop** [comment]
1. We do not support 3rd party sw
2. Use tesseract user forum for asking support
