### ISSUE TITLE
Portuguese Language Module?

### ISSUE THREAD

**Issue by JMW62** [tesseract-ocr/tessdata#47]
Hi, I just downloaded FreeOCR (version 5.41//Tesseract v3), but when I tried the Portuguese language module for the Tesseract OCR available on this site it seems to cause a problem with the OCR: i.e. "tesseract.exe has stopped working." I tried versions 4 and 3.04 of the language module (the program recommends above 2), but both cause the same problem? So, I tried the built-in English language OCR and that works not problem (except of course that it makes mistakes because it doesn't recognise the language)! I noticed when I opened the language folder of the software that por.traineddata is much larger (20,956kb) than any of the pre-installed languages (2-3,000kb)? Any suggestions?

Thanks!

**Comment by Shreeshrii** [comment]
Try gImageReader

Links at https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM

This will work with 4.0 traineddata.

- excuse the brevity, sent from mobile

**Comment by JMW62** [comment]
Ok, that works, thanks!

2017-01-28 3:46 GMT-02:00 Shreeshrii <notifications@github.com>:

> Try gImageReader
>
> Links at https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM
>
> This will work with 4.0 traineddata.
>
> - excuse the brevity, sent from mobile
>

**Comment by ade531001** [comment]
Please provide clearer instructions. Exactly same version and issue.

**Comment by amitdo** [comment]
We don't support FreeOCR.

The right place to ask questions is [our forum](https://groups.google.com/d/forum/tesseract-ocr).

@zdenop, please close this issue.
