### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by tom111** [tesseract-ocr/tessdata#5]
While it is good to have this data up here on github, it would be helpful for Linux distributions if you could tag a release, so that there is a definite set of files that distributions can distribute.  Our mirror infrastructure should not mirror "the latest version of whatever is there", and for security reasons we would also like to check by hashing that what we distribute to users tomorrow is the same that we distributed yesterday.

**Comment by zdenop** [comment]
fixed. See https://github.com/tesseract-ocr/tessdata/releases/tag/3.04.00
