### ISSUE TITLE
Brew gets stuck cloning.

### ISSUE THREAD

**Issue by amtlab** [tesseract-ocr/tessdata#50]
I'm not sure what the cause is.
brew install tesseract --HEAD
Everything goes well until when it tries to clone https://github.com/tesseract-ocr/tessdata.git.
remote: Counting objects: 111, done.
remote: Compressing objects: 100% (111/111), done.
Receiving objects:  10% (12/111), 79.01 MiB | 11.95 MiB/s            
Then it gets stuck.
Thank you for the help in advance!

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support
