### ISSUE TITLE
ara.traineddata init failed

### ISSUE THREAD

**Issue by Xugter** [tesseract-ocr/tessdata#51]
I can't init TessBaseAPI with ara.traineddata. Other traineddata is ok. Is there anyone have the same issue?

**Comment by nouhahammami** [comment]
@Xugter it's ok for me, i'm using tesseract 3.05 with android, but i have a problem using the ara.traindata, the traindata for arabic can't read the digit number (123456789)

**Comment by ros7784** [comment]
@Xugter  I have the same issue.  Have you found solution?

**Comment by amitdo** [comment]
Arabic in 3.0x uses the Cube engine. You need to download the cube files and move them to the same folder where the ara.traineddata is located.
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#cube-data-files-for-version-304305

**Comment by ros7784** [comment]
Ok, now it works fine. Thanks @amitdo

**Comment by amitdo** [comment]
@zdenop, please close this issue.

**Comment by AbdelsalamHaa** [comment]
this is the same part of the code for the english one . the only difference is that i change the eng.traindata to ara.triandata.
the image is in textImg variable.
ic.SetImage((uchar*)textImg.data, textImg.size().width, textImg.size().height, textImg.channels(), textImg.step1());
result = ic.GetUTF8Text();
ic.Clear();

**Comment by AbdelsalamHaa** [comment]
Hi guys , I'm facing the exact same problem for tesseract 3.04 but i couldn't download the cube files . any body knows from to download . the like above also can't download.
also please what are the cube files i should download , all of them or what . 
thank you guys in advance

**Comment by AbdelsalamHaa** [comment]
okay it take around 15 min just to initialize  the ara.traineddata with the cube files as well ,any idea or suggestion
