### ISSUE TITLE
tesseract 4.0 Compiling don't work for me

### ISSUE THREAD

**Issue by oscaroxy** [tesseract-ocr/tessdata#53]
I followed the steps in https://github.com/tesseract-ocr/tesseract/wiki/Compiling#linux 
I found error written so I installed autoconf-archive and in order to resolve error with "Leptonica 1.74" I have done:

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export LIBLEPT_HEADERSDIR=/usr/local/include
export TESSDATA_PREFIX='/usr/local/share/'

./configure --with-extra-includes=/usr/local/include --with-extra-libraries=/usr/local/lib
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make

but I receive this error:

In file included from rect.h:28:0,
                 from coutln.h:26,
                 from stepblob.h:23,
                 from werd.h:28,
                 from blobbox.h:25,
                 from blobbox.cpp:25:
blobbox.h: In member function 'void TO_BLOCK::print_rows()':
blobbox.h:737:61: error: expected ')' before 'PRId32'
         tprintf("Row range (%g,%g), para_c=%g, blobcount=%" PRId32 "\n",
                                                             ^
../ccutil/tprintf.h:31:39: note: in definition of macro 'tprintf'
 #define tprintf(...) tprintf_internal(__VA_ARGS__)
                                       ^
make[2]: *** [blobbox.lo] Error 1
make[2]: Leaving directory `/home/webuser/src/tesseract-4.0/ccstruct'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/webuser/src/tesseract-4.0'
make: *** [all] Error 2

Can you help me?
thanks

**Comment by amitdo** [comment]
Please move this issue to https://github.com/tesseract-ocr/tesseract/issues
Also add more info: OS, Compiler

**Comment by Shreeshrii** [comment]
I usually use the following and it works

```
git clone https://github.com/tesseract-ocr/tesseract.git
cd tesseract
./autogen.sh
./configure
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make
sudo make install
sudo ldconfig
```

**Comment by oscaroxy** [comment]
I dowloaded the zip file, can it be different?

**Comment by amitdo** [comment]
Moved to https://github.com/tesseract-ocr/tesseract/issues/919

**Comment by stweil** [comment]
@zdenop, this issue can be closed.
