### ISSUE TITLE
Spa , Ara cube data is not working. Throws Accessviolation error

### ISSUE THREAD

**Issue by MerlinArul** [tesseract-ocr/tessdata#54]
Hi, 
  I am using Spanish, arabic trained data in tesseract, but in the statement TesseractEngine it is throwing AccessViolation Error.
![accessviolationerror](https://cloud.githubusercontent.com/assets/28805589/26488522/69f4751c-4221-11e7-9c3d-822a17ec8327.png)

One more need, I have an urgent requirement for having Accurate text extraction, So we are going to use TesseractAndCube Engine mode. For this Engine mode we need Cube.* trained data. Please provide the Cube trained data for other languages like portuguese etc., Or kindly give me the steps to train the Cube data file for other languages. 

Thanks and Regards,
Merlin

**Comment by stweil** [comment]
See [Tesseract issue 946](https://github.com/tesseract-ocr/tesseract/issues/946).
