### ISSUE TITLE
ara,spa,rus  tessdata Tesseract_cube.nn file missing

### ISSUE THREAD

**Issue by MerlinArul** [tesseract-ocr/tessdata#55]
Hi,

Lang.tesseract_cube.nn file is missing for ara, spa and rus data file. Without that file it is throwing exception for TesseractAndcube enginemode

Hi theRaysmith,
     i am in need of training cube tessdata for  other language too. please share me the step to train the Cube files.
thanks and Regards,
Merlin

**Comment by amitdo** [comment]
>i am in need of training cube tessdata for other language too. please share me the step to train the Cube files.

It will never happen, no matter how many times you ask for it.

**Comment by MerlinArul** [comment]
Ok atleast provide that tesseract_cube.nn file for ara spa and rus

**Comment by Shreeshrii** [comment]
Look in the tar files for 3.02

https://github.com/tesseract-ocr/tesseract/wiki/Data-Files

**Comment by stweil** [comment]
See also issue #54.

**Comment by amitdo** [comment]
Maybe we should remove Cube in 3.05.x ...
