### ISSUE TITLE
Add 3.05 Branch

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tessdata#58]
@zdenop Please add a 3.05 branch, so that traineddata changes for 3.0x and 4.0x can be updated separately.

**Comment by zdenop** [comment]
I am not aware about any further updates for 3.05 tessdata.
If Ray would produce new files for 3.05 we can do it at that time. Otherwise it does not make sense.

**Comment by stweil** [comment]
@zdenop, what about fixing `ita.traineddata` for 3.05? And fixing `ita` in `langdata`, too?

**Comment by Shreeshrii** [comment]
https://stackoverflow.com/questions/2816715/branch-from-a-previous-commit-using-git

https://stackoverflow.com/posts/18137009/revisions

you make 3.05 branch at https://github.com/tesseract-ocr/tessdata/commit/3cf1e2df1fe1d1da29295c9ef0983796c7958b7d

**Comment by stweil** [comment]
> make 3.05 branch at 3cf1e2d

... or get the [3.05 branch from my repo](https://github.com/stweil/tessdata/tree/3.05) (with fix for `ita.traineddata` included).

**Comment by zdenop** [comment]
@Shreeshrii: I know how to create branch ;-)
@stweil: I am not sure if it make sense to create new branch because of one simple mistake... Maybe also other can post their opinion...
