### ISSUE TITLE
I set chi_sim.traineddata, but the code throw Exception.

### ISSUE THREAD

**Issue by FattigerTao** [tesseract-ocr/tessdata#59]
tess4j version 3.4.0
my code is
`instance.setLanguage("chi_sim");//add chinese`
but throw Exception
```
Exception in thread "main" java.lang.Error: Invalid memory access
actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file .\ccutil\tessdatamanager.cpp, line 50
```
How to solve the question,please? Help me.

**Comment by amitdo** [comment]
>actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file .\ccutil\tessdatamanager.cpp, line 50

See the<a href="https://github.com/tesseract-ocr/tesseract/wiki/FAQ#actual_tessdata_num_entries_-tessdata_num_entrieserrorassert-failedin-file-ccutiltessdatamanagercpp-line-55_"> FAQ</a>

>If you get an error while running tesseract, please check if you are using the correct version of traineddata (e.g. 3.00 with 3.01). You can not use 3.01 traineddata with tesseract 3.00.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
