### ISSUE TITLE
san default psm mode skipping text

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tessdata#6]
![san-019](https://cloud.githubusercontent.com/assets/5095331/9059034/12076b72-3ac4-11e5-831f-2b9cf4b7c709.png)

---

$ tesseract --tessdata-dir /usr/share -l san san-019.png san-019
Tesseract Open Source OCR Engine v3.04.00 with Leptonica
Detected 18 diacritics

---

ज्यंग्लत्रुखीसह्स्रनामलोत्रम्- नामावळिट्.
दुर्गासहस्रनामस्तीत्रम्- १ नामाक्ळि
दुर्गासहस्रनत्मस्तीत्र्दुं'म्- २ नामावळिऽ
द्बुगसिद्द्स्रनत्मरत्तोत्रम्दकारादि (३) नामावळि

पार्वतीं ह्यो) सहम्रनम्परतोत्रम्- नामावळिऽ’

फुलकुर्व्यसहस्रनत्मक्तोत्रम्-क्ताचम्-नत्माचळिऽ

गम्यत्रीसह्स्रनत्मक्तोत्रम्-नग्मग्वळिऽ(१)

191
,213

238

300
329
355
360

363.

365

394

397-

432

457

488

491

493

517

531

**Comment by Shreeshrii** [comment]
$ tesseract --tessdata-dir /usr/share -l san san-019.png san-019-6 -psm 6
Tesseract Open Source OCR Engine v3.04.00 with Leptonica

---
All lines are processed in psm 6
---
विर्व्य 16
ज्यग्लत्रुखीसहूस्रनामरतोव्रम्- नामाव'ळिऽळू 191
दुर्गासहस्रनामस्तीत्रम्- १ नामांक्ळिन्नू ॰213
द्रुर्गासहस्रनत्मस्तीन्रम्- २ नामावळिऽ 238
द्दुगसिद्द्स्रनत्मक्तोत्रम्दकाराद्दि(३) नामाव'ळिऽ 263
ट्टुगसिहस्रनामक्तोत्रम्- ४ नामावळिइं 300
पार्वतीं ह्यो) सहस्रनामातोत्रम्- नामावळिऽ’ 329
द्दुर्गानवाक्षरीन्निशतींनत्माव'क्ति 355
द्बुर्गाष्टोत्तरङ्प्तनत्मरतोव्रम्- नामावक्ति 360
र्व्यत्मामस्वोत्रम्- नामाक्ळिऽ 363
अन्नपूण्स्सिहस्रनत्मस्तीत्रम्- नामावक्ति 365
अन्नघूर्गाष्टोत्तस्यातनामस्तीन्रम्- नामावक्ति 394
क्रुलकुर्व्यसहस्रनत्मक्तोत्रम्- कवचम्… नामावळिथ् 397-
कुमारींसहृस्रनामक्तोन्नम्- नामावळिय् 432
गङ्ग’म्यासद्वृस्रनप्मक्तोव्रम्- नाम।वक्ति` 457
गङ्ग’म्याष्टोत्तराप्तनामप्तोत्रम्- नामावळिऽ 488
गङ्गादातनप्तास्तोत्रम्- नामावक्ति 491
यमुनासहस्रनामरतोव्रम्- नम्पावळिय् 493
'शिवगङ्गासद्दृस्रनत्माव'ळि 517
गम्पत्रीसह्स्रनत्मक्तोत्रम्- नाम।व'ळिऽ (१) 531

**Comment by Shreeshrii** [comment]
Testing with 4.0 alpha on windows 10, with the image given above

- default psm 3 leads to skipping of text as before, even with LSTM i.e. -oem 4 for -l san
- Using Hindi traineddata with -l hin, -oem 4 and default psm, text is not skipped

I unpacked san.traineddata and hin.traineddata and combined the Sanskrit traineddata components along with a modified version of hin.config copied as san.config and copied it as sa4.traineddata
Now default psm 3 does not skip text during recognition.

Attached are the output files as well as a copy of the config file added to traineddata. 

Since san.config cannot be uploaded, I have renamed it as san.config.txt
[san.config.txt](https://github.com/tesseract-ocr/tessdata/files/621503/san.config.txt)

[san001-psm3-oem4.txt](https://github.com/tesseract-ocr/tessdata/files/621494/san001-psm3-oem4.txt)
[san001-psm3-oem4-sa4.txt](https://github.com/tesseract-ocr/tessdata/files/621495/san001-psm3-oem4-sa4.txt)
[san001-psm6-oem4.txt](https://github.com/tesseract-ocr/tessdata/files/621497/san001-psm6-oem4.txt)
[san001-psm6-oem4-sa4.txt](https://github.com/tesseract-ocr/tessdata/files/621498/san001-psm6-oem4-sa4.txt)
![san001](https://cloud.githubusercontent.com/assets/5095331/20748262/7c12f44c-b713-11e6-922e-ea5078366d61.png)

**Comment by theraysmith** [comment]
cbbbf96 is the first part of the fix.
The traineddata files will be updated in January with a retrain that fixes a collection of language issues.

**Comment by Shreeshrii** [comment]
@theraysmith

Thanks!

Since you are planning to retrain, I would suggest using sanskrit text from Wikisource instead of wikipedia.

https://sa.m.wikisource.org/wiki/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A5%8D%E0%A4%AF%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0%E0%A4%AE%E0%A5%8D

Also, for sample of text with vedic markings, you can use the devanagari script portion from

http://sanskritdocuments.org/doc_veda/vedamantramanjari1.html?lang=sa

http://sanskritdocuments.org/doc_veda/vedamantramanjari2.html?lang=sa
