### ISSUE TITLE
new best fas.traineddata not working

### ISSUE THREAD

**Issue by hsen-dev** [tesseract-ocr/tessdata#63]
new **fas.traineddata** not working correctly. I tried by released v4.0alpha version and latest version [[61adbdf](https://github.com/tesseract-ocr/tesseract/tree/61adbdfa4bb5f17b92f8cae30fec38e3519542a2)] of _tesseract_ code, but I received this error code:

```
Error opening data file /home/[...]/fas.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'fas'
Tesseract couldn't load any languages!
Could not initialize tesseract.
```
note that **fas.traineddata** decreased size from [10.1 MB](https://github.com/tesseract-ocr/tessdata/blob/3a94ddd47be01fd897cbe31f05cbd2301454cf8a/fas.traineddata) to [3.17 MB](https://github.com/tesseract-ocr/tessdata/blob/3a94ddd47be01fd897cbe31f05cbd2301454cf8a/best/fas.traineddata).

more tesseract version info:

```
tesseract 4.00.00alpha
 leptonica-1.74.1
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0

 Found AVX
 Found SSE
```

**Comment by Shreeshrii** [comment]
It works for me when I give tessdata_dir as part of command -  point to
your traineddata file location

time tesseract "${img_file}" "${img_file%.*}"-san-best --oem 1 --psm 6  -l
san --tessdata-dir ./tessdata/best

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by hsen-dev** [comment]
thanks. 
when I checked out other traineddata files, that worked correctly. but why does it depend on other languages traineddata? and which one?

**Comment by Shreeshrii** [comment]
The new code allows the traineddata files to be in any location, not just tessdata. And, easiest way I know is to use --tessdata-dir with the commandline.

You do need eng and osd traineddata for tesseract to run,, in addition to any languages that you wat.
