### ISSUE TITLE
Hungarian teserract file not working (hun.traineddata)

### ISSUE THREAD

**Issue by sueshan1** [tesseract-ocr/tessdata#71]
I downloaded and tried to use the Hungarian teserract file with FreeOCR (hun.traineddata). 
All versions made FreeOCR fall over. 
I downloaded the latest first, then the 2 previous ones I could find. 
None of them worked. 
Anybody knows where I can find a version that works?

**Comment by Shreeshrii** [comment]
Please post freeocr related issues in their forum.

You can try tesseract 4alpha by building from github or using the linux  binaries available in ppa or windows binaries provided by @stweil. Please see wiki for links.
