### ISSUE TITLE
Delete the old 4.00.00alpha models

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tessdata#74]
LSTM+lang models for 101 languages for 4.00.00alpha were added via https://github.com/tesseract-ocr/tessdata/commit/4592b8d453889181e01982d22328b5846765eaad on Nov, 29, 2016.

These have now been superseded by the best traineddata uploaded via https://github.com/tesseract-ocr/tessdata/commit/3a94ddd47be01fd897cbe31f05cbd2301454cf8a on August 1, 2017.

The old 4.00.00alpha  models should be deleted from the repo, so that people will use the current models instead. 

Later when the fast models are uploaded, there will be a choice between tessdata/best and tessdata/fast for 4.0.0.

**Comment by stweil** [comment]
The new models in `best` no longer include data for the old recognizer, so maybe the old models should be kept until that recognizer was removed.

**Comment by Shreeshrii** [comment]
@stweil Thanks for pointing it out. We should update the data files wiki to reflect this.

**Comment by amitdo** [comment]
I added a remark about this issue here:
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400

**Comment by Shreeshrii** [comment]
Closing issue, as lstm-best, lstm-fast and tessdata will all be separate repos (as per post by Jeff).

See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-dev/_s0TOmDlEAs/lx-0ZjJjAQAJ
