### ISSUE TITLE
Best traineddata doesn't seem to work with current nuget package

### ISSUE THREAD

**Issue by whatohyou** [tesseract-ocr/tessdata#75]
When I tried to use trained data from here,
https://github.com/tesseract-ocr/tessdata/blob/master/best/jpn_vert.traineddata

renamed as jpn.traineddata and copied to
@"./tessdata";
folder then,

{
string dataPath = @"./tessdata";
string language = @"jpn";
using (var api = new TessBaseAPI(dataPath, language, OcrEngineMode.LSTM_ONLY, PageSegmentationMode.SINGLE_BLOCK))
{
api.SetInputImage(testImagePath);
string text = api.GetUTF8Text();
RTB1.Text = text;
Clipboard.SetText(text);
}
}

Then when I run the program, I get application crashes. It says program tried to read/write protected memory.

When I change the traineddata back to original 43 Mb file then it doesn't crash the application.

However, old traineddata is not trained for vertical japanese so it is useless.

Is there a way to make it work?

**Comment by Shreeshrii** [comment]
Have you tried it with command line first? Does that work?

**Comment by whatohyou** [comment]
How do I run nuget package tesseract 4.0 lstm in command line?
I will try it immediately, if I know how.

**Comment by Shreeshrii** [comment]
the nuget package is probably not built with the latest github source. Please post your issue in that forum.

You can try windows binaries from https://github.com/UB-Mannheim/tesseract/wiki

4.0 is still in alpha testing stage and you should not expect release packages of it.

**Comment by zdenop** [comment]
We do not provide support for third part sw. Please use tesseract user forum for asking support or (better) author of nuget package.
