### ISSUE TITLE
Please do split-tarball releases for each language

### ISSUE THREAD

**Issue by ismail** [tesseract-ocr/tessdata#8]
We used to have per-language tarballs like

tesseract-ocr-3.02.ind.tar.gz
tesseract-ocr-3.02.hrv.tar.gz

etc.

This is very crucial to package these files on Linux distributions, so please release per-language traineddate tarballs again.

**Comment by Phenmod** [comment]
+1

**Comment by ismail** [comment]
We switched to one big tarball for openSUSE, closing.
