### ISSUE TITLE
Best Arabic Trained Data feedback

### ISSUE THREAD

**Issue by bmwmy** [tesseract-ocr/tessdata#80]
Hi everybody

Big improvement in recognizing Arabic text with heavy vowel diacritics but hope to give option to strip out the vowel diacritics in the output.

but unfortunately there is a bug in output letters map. Some non standard Arabic characters used in the output which will be okay for printing but not for storing document digitally, it will be considered as mistake because we use standard Arabic keyboard to write and search.
Some of these letters are
used         ی               ک
right one     ي            ك

I believe if we run find and replace we could bypass this issue 
![bug](https://user-images.githubusercontent.com/24265205/30133443-8e6635c0-935c-11e7-9ca3-9654a89401c9.png)

**Comment by smilesecond** [comment]
the same problem ?

**Comment by Shreeshrii** [comment]
Please check with traineddata from tessdata_fast and post whether you face same issue with both ara and Arabic traineddata.

**Comment by bmwmy** [comment]
No, the traineddata from tessdata_fast does not have this issue.
