### ISSUE TITLE
eng.traindata size

### ISSUE THREAD

**Issue by deepakcrk** [tesseract-ocr/tessdata#86]
I have an eng.traineddata which is having 31mb.

and I have downloaded another trained data from:

https://github.com/tesseract-ocr/tessdata_best/blob/master/eng.traineddata

which in site they have claimed that it as best, but is size is only 15mb.

May I know which is giving good accuracy 31mb eng.traineddata or 15 mb eng.traineddata ??

**Comment by stweil** [comment]
Please only report bugs here. See https://github.com/tesseract-ocr/tesseract/wiki#support.
