### ISSUE TITLE
jonathanpalma/react-native-tesseract-ocr Error: Data file not found at /storage/emulated/0/com.dvastarter/tessdata/eng.traineddata at createErrorFromErrorData 

### ISSUE THREAD

**Issue by 15011120064** [tesseract-ocr/tessdata#87]
jonathanpalma/react-native-tesseract-ocr Error: Data file not found at /storage/emulated/0/com.dvastarter/tessdata/eng.traineddata at createErrorFromErrorData (blob:http://localhost:8081/b8ee2c8d-43f7-44e7-98c8-695305b775bf:3663:17) at blob:http://localhost:8081/b8ee2c8d-43f7-44e7-98c8-695305b775bf:3615:27 at MessageQueue.__invokeCallback (blob:http://localhost:8081/b8ee2c8d-43f7-44e7-98c8-695305b775bf:4057:18) at blob:http://localhost:8081/b8ee2c8d-43f7-44e7-98c8-695305b775bf:3802:18 at MessageQueue.__guardSafe (blob:http://localhost:8081/b8ee2c8d-43f7-44e7-98c8-695305b775bf:3970:11) at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/b8ee2c8d-43f7-44e7-98c8-695305b775bf:3801:14) at http://localhost:8081/debugger-ui/debuggerWorker.js:72:58 {framesToPop: 1, code: An error occurred, stack: Error: Data file not found at /storage/emulated/0/…ocalhost:8081/debugger-ui/debuggerWorker.js:72:58, message: Data file not found at /storage/emulated/0/com.dvastarter/tessdata/eng.traineddata}

**Comment by Shreeshrii** [comment]
Which version of tesseract are you using?

**Comment by 15011120064** [comment]
add v3.04 trained data files to the appropriate folder   android/app/src/main/assets/tessdata 
My path is wrong，thanks
