### ISSUE TITLE
Which data file should use to detect watch like digit ?

### ISSUE THREAD

**Issue by joginder89** [tesseract-ocr/tessdata#9]
I am using data file for English. It is able to detect normal digit but it does not detect the digit like Digital watch. I have an image of digital watch and I want to read the digit of that digital watch. Is there any way or .traineddata file to detect these digit. How can I create .traineddata file for this requirement ?

**Comment by Robyer** [comment]
Try https://github.com/arturaugusto/display_ocr/tree/master/letsgodigital

I found it here: https://github.com/tesseract-ocr/tesseract/wiki/AddOns#community-training-projects

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support
