### ISSUE TITLE
crash visualstudio 2017 , windos 10 when tesseract 4 is add 

### ISSUE THREAD

**Issue by AbdelsalamHaa** [tesseract-ocr/tessdata#95]
i hope i'm following the correct instructor to start this issue , if i'm not please let me know what is wrong so i can avoid it .

hi , i finally install tesseract 4.0 with visual studio 2017 windiws 10 . I have used it with a smaple code and everything worked fine . now im facing this problem 
![image](https://user-images.githubusercontent.com/35866217/39036674-d53c1608-44b0-11e8-86a7-623745e1d59b.png)
i read this website and it seems like it's a problem in visual studio it self they asked to add this part of code but i still cant get it where to add this code 
https://social.msdn.microsoft.com/Forums/windows/en-US/522946b7-cb39-43b3-868d-ae9bde1a458b/application-crash-ucrtbasedll

private static void AbortHandler(int signal)
{
throw new OperationCanceledException();
}

[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate void SignalHandler(int signal);

[DllImport("ucrtbase.dll", CallingConvention = CallingConvention.Cdecl, SetLastError = true, EntryPoint = "signal")]
private static extern IntPtr SubscribeSignal(int signum, SignalHandler handler);

static void Main(string[] args)
{
 SubscribeSignal(20, AbortHandler);

 // more code
}

**Comment by zdenop** [comment]
Are you making jokes? 
1. Do you have problem with tessdata? No you don't. So why you created issue in tessdata repository?
2. Is there problem in official tesseract code? You does not report anything relevant.  So why are you creating issue in tesseract project?
