### ISSUE TITLE
ParamsModel::Incomplete line on deu.traineddata

### ISSUE THREAD

**Issue by dg583** [tesseract-ocr/tessdata#96]
When I load the deu.traineddate 

tes.TesseractEngine engine = new tes.TesseractEngine(getTessdataPath(), "deu");

I get a lot of "ParamsModel::Unknown Parameter" and "ParamsModel::Incomplete line" in the console. When I choose "eng" as language everything works as expected - but unfortunally without the german Umlauts

**Comment by dg583** [comment]
I'm using V3. 

No problem when I use data from [https://github.com/tesseract-ocr/tessdata_best](url)

**Comment by dg583** [comment]
Hi @Shreeshrii,

dosn't work. I still got ParamsModel-Error in the Console. But after a while the output stops and I get the expected result...

Can't find V4.0.0-beta for .net

**Comment by Shreeshrii** [comment]
Please check whether you get same error while using tesseract via command line.

**Comment by Shreeshrii** [comment]
https://stackoverflow.com/questions/41160539/tesseract-error-params-modelincomplete-line-error

If you are using tesseract version 3, you need to use compatible traineddata files.

**Comment by Shreeshrii** [comment]
tesseract-4.0.0-beta is working fine with all three traineddata files for `deu`

```
# tesseract -v
tesseract 4.0.0-beta.1-192-g3c26
 leptonica-1.76.0
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libopenjp2 2.3.0
 Found AVX
 Found SSE

 # tesseract  ./tesseract-HEAD/testing/eurotext.tif -  --tessdata-dir ./tessdat_best  -l deu
Page 1
The (quick) [brown] {fox} jumps!
Over the $43,456.78 <lazy> #90 dog
& duck/goose, as 12.5% of E-mail
from aspammer@website.com is spam.
Der „schnelle” braune Fuchs springt
über den faulen Hund. Le renard brun
«rapide» saute par-dessus le chien
paresseux. La volpe marrone rapida
salta sopra il cane pigro. El zorro
marrön räpido salta sobre el perro
perezoso. A raposa marrom räpida
salta sobre o cäo preguicoso.
#
# tesseract  ./tesseract-HEAD/testing/eurotext.tif -  --tessdata-dir ./tessdata_fast  -l deu
Page 1
The (quick) [brown] {fox} jumps!
Over the $43,456.78 <lazy> #90 dog
& duck/goose, as 12.5% of E-mail
from aspammer@website.com is spam.
Der „schnelle” braune Fuchs springt
über den faulen Hund. Le renard brun
«rapide» saute par-dessus le chien
paresseux. La volpe marrone rapida
salta sopra il cane pigro. EI zorro
marrön räpido salta sobre el perro
perezoso. A raposa marrom räpida
salta sobre 0 cäo preguigoso.
#
# tesseract  ./tesseract-HEAD/testing/eurotext.tif -  --tessdata-dir ./tessdata  -l deu
Page 1
The (quick) [brown] {fox} jumps!
Over the $43,456.78 <lazy> #90 dog
& duck/goose, as 12.5% of E-mail
from aspammer@website.com is spam.
Der „schnelle” braune Fuchs springt
über den faulen Hund. Le renard brun
«rapide» saute par-dessus le chien
paresseux. La volpe marrone rapida
salta sopra il cane pigro. El zorro
marrön räpido salta sobre el perro
perezoso. A raposa marrom räpida
salta sobre o cäo preguicoso.

```
>Can't find V4.0.0-beta for .net

If problem is related to .net, please post in the forum for that.

**Comment by dg583** [comment]
I did't find These files, mentioned in the [article](https://stackoverflow.com/questions/41160539/tesseract-error-params-modelincomplete-line-error). This solved the Problem! Thank you for your Support!
