### ISSUE TITLE
ara.traineddata tesseract4.0 can't recognize

### ISSUE THREAD

**Issue by AbdelsalamHaa** [tesseract-ocr/tessdata#97]
Hi, im using tesseract 4.00 and leptonica 1.75.3 i used eng.traindata for some image with English words and it worked very well . now im trying to use the same code for arabic i used ara.traindata but it gives a weird characters. 
![image](https://user-images.githubusercontent.com/35866217/39420499-5d2f959c-4c97-11e8-9a3c-699a25dd7b08.png)

the arabic picture is this one 
![image](https://user-images.githubusercontent.com/35866217/39420606-d7751f5c-4c97-11e8-98df-01d1ef50f728.png)

btw also the stored characters in variable before printing is some other charecters but not the same as the printed one . im not sure why !???   

the part of the code is there under the prompt window in the picture

**Comment by zdenop** [comment]
We do not provide support for 3rd party/custom application. Please use tesseract user forum or reproduce issue with tesseract executable.
